### ISSUE TITLE
Some prerequisites should be optional

### ISSUE THREAD

**Issue by zafartahirov** [rdadolf/fathom#24]
I noticed there are [dependencies](http://fathom.readthedocs.io/en/latest/quickstart/) that are not needed for correct operation of the package. For example, `tqdm` is just a cool way of visualizing, but is not critical. I would consider making non-critical parts optional.

**Comment by rdadolf** [comment]
Hi Zafar,

Good seeing you at BARC. You're absolutely right about the package deps. We'd like to remove that one as well as some of the preprocessing dependencies that could probably be integrated without too much effort. If you have a pull request, I'd be happy to test it.

Thanks!

**Comment by zafartahirov** [comment]
I will definitely look into it -- next week (pulling allnighters for some deadlines right now :)
