### ISSUE TITLE
Running with TF 1.0

### ISSUE THREAD

**Issue by rajivkapoor** [rdadolf/fathom#26]
I read the paper (great read BTW!) and wanted to try the workloads out but ran into some basic issues.  I am a newbie to TF/ML but it looks like the TF scripts are not compatible with TF 1.0?  If yes then is there any plan to make them work on TF 1.0?

**Comment by rdadolf** [comment]
Hi there. Glad you enjoyed the read.

Yes, it's something I'd like to have updated. Currently, there is a team from IBM and a friend here at Harvard who I believe both have versions working. I believe I should be getting a pull request for this (and a bunch of other refactoring) in the upcoming week. No promises on an exact date, but it's in the works.

Thanks for the interest, and I'll make sure to update and close this issue when the changes are incorporated.

**Comment by rajivkapoor** [comment]
Good to hear that. Looking fwd to it.  Thanks!

**Comment by rajivkapoor** [comment]
Just a gentle ping .... any update? :)

**Comment by saketh** [comment]
Merged the upgrades from @Zzzoom in #27.

A few of the workloads still need some cleanup in TF 1.0.x, so let us know if you run into any issues.

**Comment by rajivkapoor** [comment]
Thanks! Will give it a shot here soon.
