### ISSUE TITLE
can this run on gem5 or gem5-Aladdin

### ISSUE THREAD

**Issue by jeepe** [rdadolf/fathom#36]
hello
I want to ask a question about this benchmark, can this run on gem5 or gem5-Aladdin or MARSSX86 etc. simulator. then if it can run on simulator. could you give me some documents or some websites to guide me how to do it. thank you

**Comment by saketh** [comment]
We haven't tested Fathom on those simulators, but theoretically it should be similar to getting other TensorFlow code to run.
