### ISSUE TITLE
Create pip installer

### ISSUE THREAD

**Issue by rdadolf** [rdadolf/fathom#5]
This will not be used for the modeling framework, but can be useful for other projects and for wider distribution.

**Comment by saketh** [comment]
Published pip installer (source dist only, at the moment). Seems conceptually simpler to distribute it with everything, so I included the modeling framework.

https://pypi.python.org/pypi?:action=display&name=Fathom-Workloads

The name "Fathom" was taken so the package name is "Fathom-Workloads" instead.
